# Generated by Django 3.1.7 on 2021-05-21 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_acad_colegios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignaturas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignatura', models.CharField(max_length=200, null=True)),
                ('descripcion', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
