# Generated by Django 3.0.7 on 2021-05-30 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sis_acad_colegios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clase', models.CharField(max_length=200)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_acad_colegios.Asignaturas')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_acad_colegios.Docentes')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_acad_colegios.Grupos')),
            ],
        ),
    ]
