# Generated by Django 4.0.4 on 2022-04-22 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_acad_colegios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conceptosacademicos',
            name='concepto_academico',
            field=models.CharField(max_length=40000, null=True),
        ),
    ]
