# Generated by Django 3.0.7 on 2021-05-31 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sis_acad_colegios', '0002_clases'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiantes',
            name='user',
        ),
        migrations.AddField(
            model_name='estudiantes',
            name='apellidos',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='estudiantes',
            name='correo',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='estudiantes',
            name='direccion',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='estudiantes',
            name='fecha_nacimiento',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='estudiantes',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estudiantes',
            name='nombres',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='estudiantes',
            name='telefono',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Matriculas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('Grupo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sis_acad_colegios.Grupos')),
                ('estudiante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sis_acad_colegios.Estudiantes')),
            ],
        ),
    ]
