# Generated by Django 3.0.7 on 2021-05-27 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_acad_colegios', '0002_auto_20210526_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docentes',
            name='dni',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
