# Generated by Django 4.0.4 on 2022-04-22 12:03

from django.db import migrations, models
import sis_acad_colegios.models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_acad_colegios', '0002_alter_conceptosacademicos_concepto_academico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conceptosacademicos',
            name='nota_maxima',
            field=models.FloatField(null=True, validators=[sis_acad_colegios.models.validate_notas_conceptos_academicos]),
        ),
        migrations.AlterField(
            model_name='conceptosacademicos',
            name='nota_minima',
            field=models.FloatField(null=True, validators=[sis_acad_colegios.models.validate_notas_conceptos_academicos]),
        ),
    ]
