# Generated by Django 3.1.7 on 2021-05-22 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_acad_colegios', '0002_asignaturas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sedes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, null=True)),
                ('direccion', models.CharField(max_length=500, null=True)),
                ('telefono', models.IntegerField()),
            ],
        ),
    ]
