# Generated by Django 3.0.7 on 2021-05-31 01:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_acad_colegios', '0003_auto_20210530_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matriculas',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
