# Generated by Django 3.1.7 on 2021-05-25 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sis_acad_colegios', '0003_sedes'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreasAsignaturas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=200, null=True)),
                ('descripcion', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='asignaturas',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sis_acad_colegios.areasasignaturas'),
            preserve_default=False,
        ),
    ]
