# Generated by Django 3.0.7 on 2021-05-31 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sis_acad_colegios', '0004_auto_20210530_2004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matriculas',
            old_name='Grupo',
            new_name='grupo',
        ),
    ]
