# Generated by Django 3.0.7 on 2021-06-01 23:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sis_acad_colegios', '0007_falla_asistencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='FallasAsistencias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justificada', models.BooleanField(default=False)),
                ('observaciones', models.CharField(max_length=500, null=True)),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('clase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sis_acad_colegios.Clases')),
                ('estudiante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sis_acad_colegios.Estudiantes')),
                ('grupo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sis_acad_colegios.Grupos')),
            ],
        ),
        migrations.DeleteModel(
            name='falla_asistencia',
        ),
    ]
