# Generated by Django 3.0.7 on 2021-06-02 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sis_acad_colegios', '0008_auto_20210601_1842'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Eps',
        ),
        migrations.DeleteModel(
            name='Estratos_sociales',
        ),
        migrations.DeleteModel(
            name='Grupos_sanguineos',
        ),
        migrations.DeleteModel(
            name='Niveles_academicos_docentes',
        ),
        migrations.DeleteModel(
            name='Tipos_documentos',
        ),
        migrations.DeleteModel(
            name='Tipos_poblaciones',
        ),
    ]
