# Generated by Django 3.0.7 on 2021-06-02 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sis_acad_colegios', '0009_auto_20210602_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fallasasistencias',
            name='grupo',
        ),
    ]
