# Generated by Django 3.0.7 on 2021-06-04 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sis_acad_colegios', '0010_remove_fallasasistencias_grupo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_academico', models.IntegerField(null=True)),
                ('calificacion', models.FloatField(null=True)),
                ('clase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sis_acad_colegios.Clases')),
                ('estudiante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sis_acad_colegios.Estudiantes')),
            ],
        ),
    ]
