# Generated by Django 3.0.7 on 2021-06-04 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_acad_colegios', '0011_calificaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificaciones',
            name='nivel_desempeno',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
