# Generated by Django 3.1.7 on 2021-06-08 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sis_acad_colegios', '0012_calificaciones_nivel_desempeno'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogrosAsignaturas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto_descriptivo', models.CharField(max_length=50)),
                ('logro', models.CharField(max_length=500)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_acad_colegios.asignaturas')),
                ('grado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis_acad_colegios.gradosacademicos')),
            ],
        ),
    ]
