# Generated by Django 3.2.4 on 2021-06-08 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sis_acad_colegios', '0013_logrosasignaturas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logrosasignaturas',
            old_name='concepto_descriptivo',
            new_name='nivel_desempeno',
        ),
    ]
