# Generated by Django 3.2.4 on 2021-06-09 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sis_acad_colegios', '0014_rename_concepto_descriptivo_logrosasignaturas_nivel_desempeno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiantes_por_grupo',
            name='estudiante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sis_acad_colegios.estudiantes'),
        ),
        migrations.AlterField(
            model_name='estudiantes_por_grupo',
            name='grupo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sis_acad_colegios.grupos'),
        ),
        migrations.AlterField(
            model_name='matriculas',
            name='estudiante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sis_acad_colegios.estudiantes'),
        ),
        migrations.AlterField(
            model_name='matriculas',
            name='grupo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sis_acad_colegios.grupos'),
        ),
    ]
